services:
  mysql:
    container_name: squirrelly-server-mysql
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: test
    ports:
      - 3307:3306
    command: mysqld --mysql-native-password=ON
    volumes:
      - "./docker/mysql/createdb.sql:/docker-entrypoint-initdb.d/createdb.sql"
    build:
      context: .
      network: host
