name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_DATABASE: squirrelly_test
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          #sudo service mysql start
          #sudo mysql < ./docker/mysql/access.sql
          mysql -h mysql -uroot -ptest -e 'SHOW DATABASES'
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run test:ci
