name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          -e MYSQL_ROOT_PASSWORD=test
          -e MYSQL_DATABASE=squirrelly_test
          -e GITHUB_ACTIONS=true
          -e CI=true
          --entrypoint sh
          mysql:8
          -c "exec docker-entrypoint.sh mysqld --default-authentication-plugin=mysql_native_password"

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: mysql -h 127.0.0.1 --port=${{ job.services.mysql.ports['3306'] }} --protocol=TCP -uroot -ptest -e 'STATUS'
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run migration:test
      - run: npm run test:ci
