name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          -e MYSQL_ROOT_PASSWORD=test
          -e MYSQL_DATABASE=squirrely_test
          -e GITHUB_ACTIONS=true
          -e CI=true
          --entrypoint mysqld
          mysql:8
          -c "--default-authentication-plugin=mysql_native_password"

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          #sudo service mysql start
          #sudo mysql < ./docker/mysql/access.sql
          echo ${{ job.services.mysql.ports['3306'] }}
          mysql -h 127.0.0.1 -uroot -ptest --port=${{ job.services.mysql.ports['3306'] }} --protocol=TCP -e 'SHOW DATABASES'
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run test:ci
